<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class EmployeesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('employees')->delete();

        DB::table('employees')->insert(array (
            0 =>
                array (
                    'id' => 1,
                    'code' => '312',
                    'name' => 'Tạ Văn Toại',
                    'img_path' => 'dist/employee_img/toaitv.jpeg',
                    'private_email' => null,
                    'company_email' => 'tavantoai@honghafeed.com.vn',
                    'phone' => '0999999999',
                    'relative_phone' => '0999999999',
                    'date_of_birth' => '1984-01-01',
                    'cccd' => '0999999999',
                    'issued_date' => '1984-01-01',
                    'issued_by' => 'công an thành phố Hà Nội',
                    'gender' => 'Nam',
                    'address' => 'số 1',
                    'commune_id' => 1,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '15 năm',
                    'join_date' => '2014-01-01',
                    'marriage_status' => 'Kết hôn',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            1 =>
                array (
                    'id' => 2,
                    'code' => '912',
                    'name' => 'Nguyễn Văn Cường',
                    'img_path' => 'dist/employee_img/cuongnv.jpeg',
                    'private_email' => null,
                    'company_email' => 'nguyenvancuong@honghafeed.com.vn',
                    'phone' => '0999999998',
                    'relative_phone' => '0999999998',
                    'date_of_birth' => '1988-05-05',
                    'cccd' => '0999999998',
                    'issued_date' => '1984-01-01',
                    'issued_by' => 'công an tỉnh Hải Dương',
                    'gender' => 'Nam',
                    'address' => 'số 1',
                    'commune_id' => 1,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '10 năm',
                    'join_date' => '2016-09-12',
                    'marriage_status' => 'Kết hôn',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            2 =>
                array (
                    'id' => 3,
                    'code' => '1992',
                    'name' => 'Phạm Hồng Hải',
                    'img_path' => 'dist/employee_img/haiph.jpeg',
                    'private_email' => null,
                    'company_email' => 'phamhonghai@honghafeed.com.vn',
                    'phone' => '0999999997',
                    'relative_phone' => '0999999997',
                    'date_of_birth' => '1988-01-01',
                    'cccd' => '0999999997',
                    'issued_date' => '1988-01-01',
                    'issued_by' => 'công an tỉnh Thái Nguyên',
                    'gender' => 'Nam',
                    'address' => 'số 1',
                    'commune_id' => 2,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '10 năm',
                    'join_date' => '2020-01-01',
                    'marriage_status' => 'Kết hôn',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            3 =>
                array (
                    'id' => 4,
                    'code' => '2142',
                    'name' => 'Bùi Thị Nụ',
                    'img_path' => 'dist/employee_img/nubt.jpeg',
                    'private_email' => null,
                    'company_email' => 'buithinu@honghafeed.com.vn',
                    'phone' => '0999999996',
                    'relative_phone' => '0999999996',
                    'date_of_birth' => '1989-01-01',
                    'cccd' => '0999999996',
                    'issued_date' => '1989-01-01',
                    'issued_by' => 'công an tỉnh Nam Định',
                    'gender' => 'Nữ',
                    'address' => 'số 1',
                    'commune_id' => 3,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '10 năm',
                    'join_date' => '2021-01-01',
                    'marriage_status' => 'Kết hôn',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            4 =>
                array (
                    'id' => 5,
                    'code' => '2199',
                    'name' => 'Trần Xuân Trường',
                    'img_path' => 'dist/employee_img/truongtx.jpeg',
                    'private_email' => null,
                    'company_email' => 'tranxuantruong@honghafeed.com.vn',
                    'phone' => '0999999995',
                    'relative_phone' => '0999999995',
                    'date_of_birth' => '1998-01-01',
                    'cccd' => '0999999995',
                    'issued_date' => '1998-01-01',
                    'issued_by' => 'công an tỉnh Hà Nam',
                    'gender' => 'Nam',
                    'address' => 'số 1',
                    'commune_id' => 4,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '3 năm',
                    'join_date' => '2022-01-01',
                    'marriage_status' => 'Kết hôn',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            5 =>
                array (
                    'id' => 6,
                    'code' => '468',
                    'name' => 'Phạm Thành Thứ',
                    'img_path' => 'dist/employee_img/thupt.jpeg',
                    'private_email' => null,
                    'company_email' => 'phamthanhthu@honghafeed.com.vn',
                    'phone' => '0999999994',
                    'relative_phone' => '0999999994',
                    'date_of_birth' => '1983-01-01',
                    'cccd' => '0999999994',
                    'issued_date' => '1983-01-01',
                    'issued_by' => 'công an tỉnh Hà Nam',
                    'gender' => 'Nam',
                    'address' => 'số 1',
                    'commune_id' => 5,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '15 năm',
                    'join_date' => '2015-01-01',
                    'marriage_status' => 'Kết hôn',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            6 =>
                array (
                    'id' => 7,
                    'code' => '353',
                    'name' => 'Ngô Tiến Trung',
                    'img_path' => 'dist/employee_img/trungnt.jpeg',
                    'private_email' => null,
                    'company_email' => 'ngotientrung@honghafeed.com.vn',
                    'phone' => '0999999993',
                    'relative_phone' => '0999999993',
                    'date_of_birth' => '1987-01-01',
                    'cccd' => '0999999993',
                    'issued_date' => '1987-01-01',
                    'issued_by' => 'công an tỉnh Nam Định',
                    'gender' => 'Nam',
                    'address' => 'số 1',
                    'commune_id' => 5,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '10 năm',
                    'join_date' => '2012-01-01',
                    'marriage_status' => 'Kết hôn',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            7 =>
                array (
                    'id' => 8,
                    'code' => '2159',
                    'name' => 'Nguyễn Văn Thắng',
                    'img_path' => 'dist/employee_img/thangnv.jpeg',
                    'private_email' => null,
                    'company_email' => 'nguyenvanthang@honghafeed.com.vn',
                    'phone' => '0999999992',
                    'relative_phone' => '0999999992',
                    'date_of_birth' => '1996-01-01',
                    'cccd' => '0999999992',
                    'issued_date' => '1987-01-01',
                    'issued_by' => 'công an tỉnh Hà Nam',
                    'gender' => 'Nam',
                    'address' => 'số 1',
                    'commune_id' => 6,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '3 năm',
                    'join_date' => '2023-01-01',
                    'marriage_status' => 'Kết hôn',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            8 =>
                array (
                    'id' => 9,
                    'code' => '226',
                    'name' => 'Cao Xuân Thuyên',
                    'img_path' => 'dist/employee_img/thuyencx.jpeg',
                    'private_email' => null,
                    'company_email' => 'caoxuanthuyen@honghafeed.com.vn',
                    'phone' => '0999999991',
                    'relative_phone' => '0999999991',
                    'date_of_birth' => '1986-01-01',
                    'cccd' => '0999999991',
                    'issued_date' => '1986-01-01',
                    'issued_by' => 'công an tỉnh Hà Nam',
                    'gender' => 'Nam',
                    'address' => 'số 1',
                    'commune_id' => 6,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '13 năm',
                    'join_date' => '2011-01-01',
                    'marriage_status' => 'Kết hôn',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            9 =>
                array (
                    'id' => 10,
                    'code' => '240',
                    'name' => 'Phạm Xuân Giáp',
                    'img_path' => 'dist/employee_img/giappx.jpeg',
                    'private_email' => null,
                    'company_email' => 'phamxuangiap@honghafeed.com.vn',
                    'phone' => '0999999990',
                    'relative_phone' => '0999999990',
                    'date_of_birth' => '1985-01-01',
                    'cccd' => '0999999990',
                    'issued_date' => '1985-01-01',
                    'issued_by' => 'công an tỉnh Thái Bình',
                    'gender' => 'Nam',
                    'address' => 'số 1',
                    'commune_id' => 6,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '15 năm',
                    'join_date' => '2011-01-01',
                    'marriage_status' => 'Kết hôn',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            10 =>
                array (
                    'id' => 11,
                    'code' => '233',
                    'name' => 'Phạm Thị Thúy',
                    'img_path' => 'dist/employee_img/thuypt.jpeg',
                    'private_email' => null,
                    'company_email' => 'phamthithuy@honghafeed.com.vn',
                    'phone' => '0999999989',
                    'relative_phone' => '0999999989',
                    'date_of_birth' => '1989-01-01',
                    'cccd' => '0999999989',
                    'issued_date' => '1989-01-01',
                    'issued_by' => 'công an tỉnh Hà Nam',
                    'gender' => 'Nữ',
                    'address' => 'số 1',
                    'commune_id' => 7,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '10 năm',
                    'join_date' => '2011-01-01',
                    'marriage_status' => 'Kết hôn',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            11 =>
                array (
                    'id' => 12,
                    'code' => '275',
                    'name' => 'Đinh Thị Ngà',
                    'img_path' => 'dist/employee_img/ngadt.jpeg',
                    'private_email' => null,
                    'company_email' => 'dinhthinga@honghafeed.com.vn',
                    'phone' => '0999999988',
                    'relative_phone' => '0999999988',
                    'date_of_birth' => '1984-01-01',
                    'cccd' => '0999999988',
                    'issued_date' => '1984-01-01',
                    'issued_by' => 'công an tỉnh Hà Nam',
                    'gender' => 'Nữ',
                    'address' => 'số 1',
                    'commune_id' => 8,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '15 năm',
                    'join_date' => '2011-01-01',
                    'marriage_status' => 'Kết hôn',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            12 =>
                array (
                    'id' => 13,
                    'code' => '248',
                    'name' => 'Trần Thị Thu Hương',
                    'img_path' => 'dist/employee_img/huongttt.jpeg',
                    'private_email' => null,
                    'company_email' => 'tranthithuhuong@honghafeed.com.vn',
                    'phone' => '0999999987',
                    'relative_phone' => '0999999987',
                    'date_of_birth' => '1990-01-01',
                    'cccd' => '0999999987',
                    'issued_date' => '1990-01-01',
                    'issued_by' => 'công an tỉnh Hà Nam',
                    'gender' => 'Nữ',
                    'address' => 'số 1',
                    'commune_id' => 8,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '10 năm',
                    'join_date' => '2011-01-01',
                    'marriage_status' => 'Kết hôn',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            13 =>
                array (
                    'id' => 14,
                    'code' => '252',
                    'name' => 'Nguyễn Thị Thiết',
                    'img_path' => 'dist/employee_img/thietnt.jpeg',
                    'private_email' => null,
                    'company_email' => 'nguyenthithiet@honghafeed.com.vn',
                    'phone' => '0999999986',
                    'relative_phone' => '0999999986',
                    'date_of_birth' => '1990-01-01',
                    'cccd' => '0999999986',
                    'issued_date' => '1990-01-01',
                    'issued_by' => 'công an tỉnh Hà Nam',
                    'gender' => 'Nữ',
                    'address' => 'số 1',
                    'commune_id' => 3,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '10 năm',
                    'join_date' => '2011-01-01',
                    'marriage_status' => 'Kết hôn',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            14 =>
                array (
                    'id' => 15,
                    'code' => '554',
                    'name' => 'Cao Thị Phượng',
                    'img_path' => 'dist/employee_img/phuongct.jpeg',
                    'private_email' => null,
                    'company_email' => 'caothiphuong@honghafeed.com.vn',
                    'phone' => '0999999985',
                    'relative_phone' => '0999999985',
                    'date_of_birth' => '1991-01-01',
                    'cccd' => '0999999985',
                    'issued_date' => '1991-01-01',
                    'issued_by' => 'công an tỉnh Hà Nam',
                    'gender' => 'Nữ',
                    'address' => 'số 1',
                    'commune_id' => 4,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '10 năm',
                    'join_date' => '2013-01-01',
                    'marriage_status' => 'Kết hôn',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            15 =>
                array (
                    'id' => 16,
                    'code' => '868',
                    'name' => 'Đỗ Thị Thu Hương',
                    'img_path' => 'dist/employee_img/huongdtt.jpeg',
                    'private_email' => null,
                    'company_email' => 'dothithuhuong@honghafeed.com.vn',
                    'phone' => '0999999984',
                    'relative_phone' => '0999999984',
                    'date_of_birth' => '1990-01-01',
                    'cccd' => '0999999984',
                    'issued_date' => '1990-01-01',
                    'issued_by' => 'công an tỉnh Hà Nam',
                    'gender' => 'Nữ',
                    'address' => 'số 1',
                    'commune_id' => 3,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '10 năm',
                    'join_date' => '2016-01-01',
                    'marriage_status' => 'Kết hôn',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            16 =>
                array (
                    'id' => 17,
                    'code' => '557',
                    'name' => 'Nguyễn Thị Thúy Nga',
                    'img_path' => 'dist/employee_img/ngantt.jpeg',
                    'private_email' => null,
                    'company_email' => 'nguyenthithuynga@honghafeed.com.vn',
                    'phone' => '0999999983',
                    'relative_phone' => '0999999983',
                    'date_of_birth' => '1993-01-01',
                    'cccd' => '0999999983',
                    'issued_date' => '1993-01-01',
                    'issued_by' => 'công an tỉnh Hà Nam',
                    'gender' => 'Nữ',
                    'address' => 'số 1',
                    'commune_id' => 7,
                    'temporary_address' => null,
                    'temporary_commune_id' => null,
                    'experience' => '10 năm',
                    'join_date' => '2015-01-01',
                    'marriage_status' => 'Kết hôn',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
        ));
    }
}
